papiro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('descriptor.urls')),
]

descriptor/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _


class Api(models.Model):
    name = models.CharField(_('name'), max_length=60, unique=True)
    description = models.TextField(_('description'), blank=True)
    enabled = models.BooleanField(_('enabled'), default=True)

    def __str__(self):
        return self.name


class Service(models.Model):
    SERVICE_STATUS = [
        ('ST', _('under study').capitalize()),
        ('DV', _('under development').capitalize()),
        ('HM', _('under test').capitalize()),
        ('DP', _('deployed').capitalize()),
    ]

    HTTP_METHODS = [
        ('GET', 'GET'),
        ('POST', 'POST'),
        ('PUT', 'PUT'),
        ('DELETE', 'DELETE'),
        ('PATCH', 'PATCH'),
    ]

    api = models.ForeignKey(Api, on_delete=models.CASCADE, related_name='services')
    name = models.CharField(_('name'), max_length=120)
    description = models.TextField(_('description'), blank=True, default="")
    status = models.CharField(max_length=2, choices=SERVICE_STATUS, blank=False, null=False)
    iib_service_number = models.PositiveIntegerField(_('iib service number'), blank=True, null=True, help_text=_('Insert IIB Service Number if already available. '))
    iib_service_version_number = models.PositiveSmallIntegerField(_('iib service version number'), blank=True, null=True)
    endpoint_uri = models.CharField(_('endpoint uri'), max_length=200, blank=True, default="")
    http_method = models.CharField(_('method'), max_length=6, blank=False, null=False, choices=HTTP_METHODS)
    enabled = models.BooleanField(_('enabled'), default=True)
    tag = models.PositiveSmallIntegerField(_('tag'), default=0)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('service')
        verbose_name_plural = _('services')
        ordering = ['name']

    def is_snapshot(self):
        return self.tag == 0


class ParameterGroup(models.Model):
    PARAMETER_GROUP_TYPE = [
        ('000', _('request').capitalize()),
        ('200', _('response 200 - ok').capitalize()),
        ('400', _('response 400 - error').capitalize()),
        ('403', _('response 403 - forbidden').capitalize()),
        ('500', _('response 500 - server error').capitalize()),
    ]

    type = models.CharField(_('parameter type'), max_length=3, blank=False, null=False, choices=PARAMETER_GROUP_TYPE)
    service = models.ForeignKey(Service, on_delete=models.CASCADE, related_name='parameter_groups')

    def __str__(self):
        return f"{self.service.name} - {self.get_type_display()}"

    class Meta:
        verbose_name = _('parameter group')
        verbose_name_plural = _('parameter groups')


class Parameter(models.Model):
    FORMATS = [
        ('AN', _('alphanumeric').capitalize()),
        ('NB', _('number').capitalize()),
        ('AR', _('array').capitalize()),
        ('OB', _('object').capitalize()),
    ]

    name = models.CharField(_('name'), max_length=40)
    format = models.CharField(_('format'), max_length=2, blank=False, null=False, choices=FORMATS)
    size = models.CharField(_('size'), max_length=20)
    required = models.BooleanField(_('required'), default=True)
    domain_rules = models.CharField(_('domain rules'), max_length=120, blank=True, default="")
    parameter_parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='parameter_children', blank=True, null=True)
    parameter_group = models.ForeignKey(ParameterGroup, on_delete=models.CASCADE, related_name='parameters')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('parameter')
        verbose_name_plural = _('parameter')


class TagSignature(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE, related_name='tag_signatures')
    first_signer = models.ForeignKey(User, related_name='First_signer', on_delete=models.CASCADE, null=False)
    second_signer = models.ForeignKey(User, related_name='Second_signer', on_delete=models.CASCADE, null=True, default=None)
    first_signature_signed_at = models.DateTimeField(null=True)
    second_signature_signed_at = models.DateTimeField(null=True)

    def is_closed(self):
        return (self.first_signer is not None) and (self.second_signer is not None)

    def __str__(self):
        if self.first_signer and self.second_signer:
            return f"{_('Signed by')} {self.first_signer.username}  {_(' and ')} {self.second_signer.username}" 
        else:
            return f"{_('Signed by')} {self.first_signer.username}"

    class Meta:
        verbose_name = _('parameter')
        verbose_name_plural = _('parameter')

templates/papiro/base.html
<!DOCTYPE html>
<html lang="pt-br" >
<head>
    <!-- linked styles -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;1,100;1,300;1,400;1,500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="https://jqueryui.com/jquery-wp-content/themes/jqueryui.com/style.css">

    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>

    {% block header_insert %} {% endblock %}

    <style media="screen">
        {% block css_internal %}{% endblock %}
    </style>

    <script type="text/javascript">
        $(document).ready(function(){
            {% block jquery_internal %}{% endblock %}
        });
    </script>
</head>

<body>
    <div id="main">
        <!-- Header -->
        {% block main %}{% endblock %}
    </div>
    <!-- END Main -->
</body>
</html>

templates/papiro/index.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html lang="pt-br" >
<head>
    <title>Papiro | {% trans "API Administration" %}</title>

    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="robots" content="NONE,NOARCHIVE">

    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;1,100;1,300;1,400;1,500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=VT323&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="https://jqueryui.com/jquery-wp-content/themes/jqueryui.com/style.css">

    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'js/popup.js' %}"></script>

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'img/site.webmanifest' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/papiro.css' %}?addaddf">

    <script type="text/javascript">
        $( function() {
            /* The iframe default src is an empty page /api/noservices/
               If there is at least one service, sets the iframe src to this first service.*/
            const numServices = $(".open-in-iframe").length;
            if(numServices > 0){
                firstService = $(".open-in-iframe")[0];
                $("#iframe_details").attr("src", $(firstService).attr("href"));
            }

            /* Sets jQuery UI Accordion up */
            $( "#accordion" ).accordion({
                heightStyle: "content",
                collapsible: true,
                animate: 100
            });

            $("a.open-in-iframe").click(function(){
                $("#iframe_details").attr("src", $(this).attr("href"));
                return false;
            });

        });
    </script>
</head>

<body>
    <header>
        <h1>
            <a href="/api/">
                <img src="{% static 'img/logo.png'%}" />
            </a>
        </h1> 

        <div>
                {% trans "Welcome" %}, <strong>{{user}}</strong>. <a href="/admin/logout/">{% trans "Logout" %}</a>
        </div>
    </header>

    <div class="content">
        <aside>
            <h1>{% trans 'Projects' %}</h1>
            <div id="accordion">
                {% if api_list %}
                    {% for api in api_list %}
                        <h3>{{ api.name }} <span class="services">{{api.services.count}} serviço{{ api.services.count|pluralize:",s" }}</span></h3>
                        <div>
                            {% for service in api.services.all %} 
                                {% if service.is_snapshot %}
                                    <a href="/api/{{api.id}}/service/{{service.name}}/" class="open-in-iframe"><span class="http-method {{service.http_method|lower}}">{{service.http_method}}</span>{{service.name}}</a>
                                {% endif %}
                            {% endfor %}

                            <button type="button" data-href="{% url 'popup_add_service' api.id %}" class="add jpopup">
                                {% trans "Add service" %}
                            </button>
                        </div>
                    {% endfor %}
                {% else %}
                    <span class="empty">{% trans "No API found" %}</span>
                {% endif %}
            </div>
        </aside>

        <main>
            <iframe 
                id="iframe_details"
                src="/api/noservices/"
                style="width: 100%;height: 100%;padding: 0; margin: 0;"
                frameborder=0>
            </iframe>
        </main>
    </div>
</body>
</html>

templates/papiro/noservices.html
{% extends "papiro/base.html" %}
{% load static %}
{% load i18n %}

{% block header_insert %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/service-details.css' %}">
{% endblock %}

{% block main %}
<div id="title">
    <div>
        <h1>Papiro - {% trans 'API administration' %}</h1>
    </div>
</div>
<p style="padding:20px;">
    {% trans 'Select a service from the navigation menu on the left' %}
</p>
{% endblock %}

templates/papiro/popup_new_api.html
{% load i18n %}
<!DOCTYPE html>
<html lang="pt-br" >
<head>
    <title>{% trans "Add service" %} | Papiro</title>
    <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css">

    <script type="text/javascript" src="/admin/jsi18n/"></script>
    <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
    <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
    <script type="text/javascript" src="/static/admin/js/core.js"></script>
    <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
    <script type="text/javascript" src="/static/admin/js/actions.js"></script>
    <script type="text/javascript" src="/static/admin/js/urlify.js"></script>
    <script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
    <script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>

    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">
    <meta name="robots" content="NONE,NOARCHIVE">
    <style media="screen">
        #id_size {max-width: 60px;flex:none;}
        #id_format {max-width: 300px;flex:none;}
    </style>
    <script type="text/javascript">
        var $ = django.jQuery;
        $("document").ready(function(){
            $("#id_api").val({{api.id}});
            $("#id_api").parent().parent().hide();
        });
    </script>
</head>


<body class="popup  app-descriptor model-service change-form" data-admin-utc-offset="0">
    <div id="container">
        <div id="content" class="colM">
            <h1>{% trans "New Api Project" %}</h1>
            <div id="content-main">
            <form action="" method="post" autocomplete="off">
                {% csrf_token %}
                <table>
                {{ form.as_table }}
                </table>
                <br class="clear">
                <input type="submit" value="{% trans 'Submit' %}">
            </form>
        </div>
        <br class="clear">
    </div>
</body>
</html>

templates/papiro/popup_new_parameter.html
{% load i18n %}
<!DOCTYPE html>
<html lang="pt-br" >
<head>
    <title>{% trans "Add parameter" %} | Papiro</title>
    <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css">

    <script type="text/javascript" src="/admin/jsi18n/"></script>
    <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
    <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
    <script type="text/javascript" src="/static/admin/js/core.js"></script>
    <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
    <script type="text/javascript" src="/static/admin/js/actions.js"></script>
    <script type="text/javascript" src="/static/admin/js/urlify.js"></script>
    <script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
    <script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>

    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">
    <meta name="robots" content="NONE,NOARCHIVE">
    <style media="screen">
        #id_size {max-width: 60px;flex:none;}
        #id_format {max-width: 300px;flex:none;}
    </style>
    <script type="text/javascript">
        var $ = django.jQuery;
        $("document").ready(function(){
            $("#id_parameter_group").val({{parameter_group_id}});
            $("#id_parameter_group").parent().parent().hide();

            $("#id_parameter_parent").parent().parent().hide();

            var parent_id = "{{parent_id}}";
            if(parent_id.length && parent_id != "None"){
                $("#id_parameter_parent").val(parent_id);
            }
        });
    </script>
</head>

<body class="popup  app-descriptor model-parameter change-form" data-admin-utc-offset="0">
    <div id="container">
        <div id="content" class="colM">
            <h1>Adicionar parâmetro</h1>
            <div id="content-main">
            <form action="" method="post" autocomplete="off">
                {% csrf_token %}
                <table>
                {{ form.as_table }}
                </table>
                <br class="clear">
                <input type="submit" value="{% trans 'Submit' %}">
            </form>
        </div>
        <br class="clear">
    </div>
</body>
</html>

templates/papiro/popup_new_service.html
{% load i18n %}
<!DOCTYPE html>
<html lang="pt-br" >
<head>
    <title>{% trans "Add service" %} | Papiro</title>
    <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css">

    <script type="text/javascript" src="/admin/jsi18n/"></script>
    <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
    <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
    <script type="text/javascript" src="/static/admin/js/core.js"></script>
    <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
    <script type="text/javascript" src="/static/admin/js/actions.js"></script>
    <script type="text/javascript" src="/static/admin/js/urlify.js"></script>
    <script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
    <script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>

    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">
    <meta name="robots" content="NONE,NOARCHIVE">
    <style media="screen">
        #id_size {max-width: 60px;flex:none;}
        #id_format {max-width: 300px;flex:none;}
    </style>
    <script type="text/javascript">
        var $ = django.jQuery;
        $("document").ready(function(){
            $("#id_api").val({{api.id}});
            $("#id_api").parent().parent().hide();
        });
    </script>
</head>


<body class="popup  app-descriptor model-service change-form" data-admin-utc-offset="0">
    <div id="container">
        <div id="content" class="colM">
            <h1>{% trans "Add service to" %} {{ api.name }}</h1>
            <div id="content-main">
            <form action="" method="post" autocomplete="off">
                {% csrf_token %}
                <table>
                {{ form.as_table }}
                </table>
                <br class="clear">
                <input type="submit" value="{% trans 'Submit' %}">
            </form>
        </div>
        <br class="clear">
    </div>
</body>
</html>

templates/papiro/service_detail.html
{% extends "papiro/base.html" %}
{% load static %}
{% load i18n %}

{% block header_insert %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/service-details.css' %}?09qejuuuuw31ad9">
    <script src="{% static 'js/popup.js' %}"></script>
{% endblock %}

{% block jquery_internal %}
    $("#change_service_version").click(function(){
        var tag = $("#service_tags").val();
        if(tag==0){
            document.location.href = "{% url 'service_detail_by_name' service.api.id service.name %}";
        } else {
            document.location.href = "{% url 'service_detail_by_name' service.api.id service.name %}tag/" + tag;
        }
    });

    function csrfSafeMethod(method) {
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", $("#_csrf").val());
            }
        }
    });

    $("#commit_tag").click(function(){
        if(confirm("{% trans 'Are you sure you want close this version and generate a new tag?'%}")){
            var _url = "{% url 'create_new_tag' service.id %}";
            var _data = '{"commit": "true" }';
            var returned_version;
            console.log(_url);
            console.log(_data);
            $.ajax({
                url : _url,
                type : 'POST',
                data : _data,
                headers : {
                    'Content-Type' : 'application/json'
                },
                success : function(response, textStatus, jqXhr) {
                    console.log("Successfully Posted!", textStatus);
                    returned_version = response;
                    console.log(returned_version);
                },
                error : function(jqXHR, textStatus, errorThrown) {
                    console.log("The following error occured: " + textStatus, errorThrown);
                },
                complete : function() {
                    document.location.href = "{% url 'service_detail_by_name' service.api.id service.name %}/tag/" + returned_version;
                }
            });
        }
    });
{% endblock %}

{% block main %}
<div id="title">
    <div>
        <h1>{{ service.name }} </h1>
        <em>[{% if service.tag == 0 %}SNAPSHOT{% else %}v. {{service.tag}}{% endif %}]</em>
        {% if tag_signature %}
            {% if tag_signature.is_closed == False %}
                <span class="status"> {% trans 'pending' %}</span>
            {% endif %}
        {% endif %}
    </div>

    <ul id="tag-select">
        <li>
            {% trans 'Version' %}: 
            <select id="service_tags">
                {% for svc in all_services %}
                    <option value="{{svc.tag}}" {% if svc.tag == service.tag %}selected{% endif %}>{% if svc.tag == 0 %}SNAPSHOT{% else %}{{svc.tag}}{% endif %}</option>
                {% endfor %}
            </select>
            <button type="button" id="change_service_version" class="go">{% trans "Go" %}</button>
        </li>
    </ul>
</div>


<form id="service_form" novalidate="" style="display: none;">
    <input type="hidden" id="_csrf" value="{{csrf_token}}">
</form>


<div id="service_attributes">
    <div>
        <div>
            <span name="description" id="description" class="editable" data-field-type="textarea" data-field="description" data-field-label="{% trans 'description' %}" data-id="{{service.id}}">
                {% if service.description %}
                    {{ service.description }}
                {% else %}
                    <em>{% trans "Click to add description" %}</em>
                {% endif %}
            </span>
        </div>
        <!--
        <div>
            <span name="status" id="id_status" class="editable" data-field-type="select" data-field="status" data-field-label="{% trans 'status' %}" data-id="{{service.id}}">
                {{ service.get_status_display }}
            </span>
        </div>
        -->
        <div>    
            {% if service.iib_service_number %}
                <span name="iib" id="iib">
                    {{ service.iib_service_number }}
                    {% if service.iib_service_number %}
                            v.{{ service.iib_service_version_number }}
                    {% endif %}
                </span>
            {% endif %}
        </div>
        <div id="endpoint">
                <span class="http_method {{service.http_method|lower}}">
                    {{service.http_method}}
                </span>
                <span class="url">
                    {% if service.endpoint_uri %}
                        {{ service.endpoint_uri }}
                    {% else %}
                        {% trans 'No endpoint' %}
                    {% endif %}
                </span>
            </span>
        </div>
    </div>
</div>

{% if parameter_groups %}
    {% for parameter_group in parameter_groups %}
    <div class="parameter-group" id="group_{{parameter_group.id}}">
        <div class="results">
            <table id="result_list">
                <caption class="{% if parameter_group.type == '088800'%}{{service.http_method|lower}}{% endif %}">
                    {{ parameter_group.get_type_display }}
                </caption>
                {% if parameter_group.parameters.all %}
                <thead>
                    <tr>
                        <th scope="col"  class="action-checkbox-column">
                            <div class="text"></div>
                            <div class="clear"></div>
                        </th>
                        <th scope="col"  class="column-name">
                            <div class="text">{% trans "name" %}</div>
                            <div class="clear"></div>
                        </th>
                        <th scope="col"  class="column-description">
                            <div class="text">{% trans "format" %}</div>
                            <div class="clear"></div>
                        </th>
                        <th scope="col"  class="column-size">
                            <div class="text">{% trans "size" %}</div>
                            <div class="clear"></div>
                        </th>
                        <th scope="col"  class="column-required">
                            <div class="text">{% trans "required" %}</div>
                            <div class="clear"></div>
                        </th>
                        <th scope="col"  class="column-domain_rules">
                            <div class="text">{% trans "domain rules" %}</div>
                            <div class="clear"></div>
                        </th>
                        <th scope="col"  class="add">
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for parameter in parameter_group.parameters.all %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ parameter.name }}</td>
                            <td>{{ parameter.get_format_display }}</td>
                            <td>{{ parameter.size }}</td>
                            <td>{{ parameter.required|yesno:"Sim,Não,Não" }}</td>
                            <td>{{ parameter.domain_rules }}</td>
                            <td>
                                {% if parameter.format == 'AR' %}
                                    <button type="button">Add</button>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td colspan="4">{% trans "no parameters yet." %}</td>
                    </tr>
                {% endif %}
                </tbody>
            </table>
        </div>
        <ul class="parameter-action">
            <li>
                {% if service.tag == 0 %}
                <!-- editable only if service tag is SNAPSHOT (0) -->
                <button type="button" data-href="{% url 'popup_add_parameter' service.id parameter_group.id %}" class="add jpopup">
                    <span class="ui-icon ui-icon-plusthick"></span>
                    {% trans "parameter" %}
                </button>
                {% endif %}
            </li>
        </ul>
    </div>
    {% endfor %}
{% else %}
    <h2>{% trans "No parameter groups yet." %}</h2>
{% endif %}
</div>

<div class="tag_control">
{% if service.tag == 0 %}
    <!-- only shows button if tag == 0 (SNAPSHOT) -->
        <div class="tag_signature">
            <h3>{% trans 'First signature' %}</h3>
            <div>
                <button id="commit_tag">{% trans 'Sign and commit tag' %}</button>
            </div>
        </div>
        <div class="tag_signature">
            <h3>{% trans 'Second signature' %}</h3>
            <div>
                <span>
                    {% trans 'Awaiting for first signature' %}
                </span>
            </div>
        </div>
{% else %}
    <!-- if not snapshot -->
    {% if tag_signature %}
        <div class="tag_signature">
            <h3>{% trans 'First signature' %}</h3>
            <div>{% trans 'Digitally signed by' %} {{tag_signature.first_signer.first_name}} {{tag_signature.first_signer.last_name}}
                {% trans ' at ' %} {{tag_signature.signed_at}}
            </div>
        </div>

        {% if tag_signature.second_signer == None %}
        <div class="tag_signature">
            <h3>{% trans 'Second signature' %}</h3>
            <div>
                <button id="confirm_tag">{% trans 'Confirm and commit tag' %}</button>
            </div>
        </div>
        {% endif %}
    {% endif %}
{% endif %}
<div class="clear"></div>

{% endblock %}

templates/papiro/services.html
{% extends "papiro/base.html" %}
{% load i18n %}


{% block title %}{{ api.name }}{% endblock %}

{% block jquery_internal %}
    var popupWindow;
    function isPopupWindowOpen(){
        if(popupWindow){
            if(popupWindow.closed) return false;
            return true;
        } else
            return false;
    }

    django.jQuery(function() {

        django.jQuery('a.jpopup').click(function() {
            if(!isPopupWindowOpen()){
                var href = django.jQuery(this).attr('href');
                popupWindow = window.open(href, 'jpopup', 'height=720, width=550, toolbar=no');
            } else {
                popupWindow.focus();
            }
            return false;
        });
    });
{% endblock %}


{% block breadcrumbs %}
    <a href="/api/">{% trans "Home" %}</a> &rsaquo; <a href="/api">{% trans "API Projects" %}</a> &rsaquo; {{ api.name }}
{% endblock %}

{% block content_main %}
    <ul class="object-tools">
        <li>
            <a href="{% url 'popup_add_service' api.id %}" class="addlink jpopup">{% trans "Add service" %}</a>
        </li>
    </ul>

    <div class="module" id="changelist">
        <div class="results">
            <table id="result_list">
                <thead>
                    <tr>
                        <th scope="col"  class="action-checkbox-column">
                           <div class="text"><span><input type="checkbox" id="action-toggle"></span></div>
                           <div class="clear"></div>
                        </th>
                        <th scope="col"  class="sortable column-name">
                           <div class="text"><a href="?o=1">{% trans "name" %}</a></div>
                           <div class="clear"></div>
                        </th>
                        <th scope="col"  class="sortable column-description">
                           <div class="text"><a href="?o=2">{% trans "description" %}</a></div>
                           <div class="clear"></div>
                        </th>
                        <th scope="col"  class="sortable column-http_method">
                           <div class="text"><a href="?o=3">{% trans "method" %}</a></div>
                           <div class="clear"></div>
                        </th>
                    </tr>
                </thead>
                <tbody>
                {% if service_list %}
                    {% for service in service_list %}
                    <tr class="row1">
                        <td class="action-checkbox"><input type="checkbox" name="_selected_action" value="1" class="action-select"></td>
                        <th class="field-name">
                            <a href="{% url 'service_detail_by_name' api.id service.name %}">{{ service.name }}</a>
                        </th>
                        <td class="field-description">{{ service.description }}</td>
                        <td class="field-http_method">{{ service.http_method }}</td>
                    </tr>
                    {% endfor %}
                {% else %}
                    <tr class="row1">
                        <td colspan="4">{% trans "No services found" %}</td>
                    </tr>
                {% endif %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}